version: '3.6'
services:
  db:
    volumes:
      - app-db-data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME}.app-db-data == true
  proxy:
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "letsencrypt:/letsencrypt/"
      - /var/run/docker.sock:/var/run/docker.sock:ro
  backend:
    volumes:
      - app-backend-data:/usr/src/app/lib/uploads/

volumes:
  letsencrypt:
  app-db-data:
  app-backend-data: