version: "3.6"
services:
  backend:
    build:
      context: ./backend
      # dockerfile: backend.dockerfile
      args:
        env: dev
  frontend:
    stdin_open: true
    tty: true
    build: 
      context: ./frontend

